### ISSUE TITLE
Clustername for discord bot isn't correctly defined

### ISSUE THREAD

**Issue by jlejeune** [kubeshop/botkube-docs#111]
## Description

Following the helm command to deploy botkube for discord:

```
helm install --version v0.12.4 botkube --namespace botkube --create-namespace \
--set communications.discord.enabled=true \
--set communications.discord.channel=<DISCORD_CHANNEL_ID> \
--set communications.discord.botID=<DISCORD_BOT_ID> \
--set communications.discord.token=<DISCORD_TOKEN> \
--set config.settings.clusterName=<CLUSTER_NAME> \
--set config.settings.kubectl.enabled=<ALLOW_KUBECTL> \
--set image.tag=v0.12.4 \
botkube/botkube
```

doesn't correctly define the k8s cluster name.

## Expected behavior

First message sent by the bot with the correct cluster name.

## Actual behavior

First message sent by the bot:
`...and now my watch begins for cluster 'not-configured'!`

## Steps to reproduce

Deploy botkube for discord using that helm command.

**Comment by jlejeune** [comment]
Actually, I think that issue affects all messaging tools.

**Comment by mszostok** [comment]
Hi @jlejeune, thanks for reporting this issue. 

A small background of this problem. Currently, we're working on v0.13.0 and that is the one of the breaking change, for more details please see https://github.com/kubeshop/botkube/issues/614.

Unfortunately, we don't have versioning on our website, yet. It's sth that will be fixed shortly https://github.com/kubeshop/botkube-docs/issues/80.

And you are right, we need to keep the old naming for now 👍 

Thanks!

**Comment by brampling** [comment]
@jlejeune Thank you very much for opening the issue and the fix PR! I would love to talk to you about how you're using BotKube if you can spare a few minutes. If you email me at blair@kubeshop.io I can send a link to set up a time.
