### ISSUE TITLE
Fix Algolia indexing

### ISSUE THREAD

**Issue by madebyrogal** [kubeshop/botkube-docs#171]
## Overview

After we've changed documentation domain Algolia configuration needs to be fixed

# AC
- [x] index is fixed
- [x] search bar is enabled

## Dev Notes
- [x] Add post on official formu https://discourse.algolia.com/t/change-domain-on-an-open-source-site/16694
- [x] request and issue on support zendesk https://support.algolia.com/hc/en-us/requests/525786

**Comment by pkosiec** [comment]
Closing as it was already resolved by @madebyrogal some time ago 👍
