### ISSUE TITLE
Rework the Examples section

### ISSUE THREAD

**Issue by josefkarasek** [kubeshop/botkube-docs#185]
## Rework the Examples section

As of now the Examples section is a collection of random tasks and screenshots.
It would be better if we give this section more order.

## Acceptance Criteria

Real-world use-cases are provided in the examples section.

## Reason

Current page is too generic and doesn't provide much value.

**Comment by pkosiec** [comment]
@brampling @josefkarasek What do you think about removing this page completely? It contains outdated screenshots (old logo and name casing). 
The "Usage" section is way more useful, and also contains some up-to-date screenshots.

**Comment by brampling** [comment]
Fine with me, it feels disconnected from the rest of the docs.
