### ISSUE TITLE
Update the Vault tutorial

### ISSUE THREAD

**Issue by mszostok** [kubeshop/botkube-docs#193]
## Description

Outdated things:

- `COMMUNICATIONS_SLACK_TOKEN` is invalid (missing group)
  - mention how to create such token (https://docs.botkube.io/configuration/#environment-variables)
- switch to socket Slack
-  install Botkube from latest release instead from cloned `main`

Test that it works e2e.

**Comment by pkosiec** [comment]
See the Slack thread: https://botkube.slack.com/archives/CG7TTBXM2/p1675302056942289 - Confirmed by two users that the updated instructions work well 🙂
