### ISSUE TITLE
Helm chart version is not updated on release job

### ISSUE THREAD

**Issue by mszostok** [kubeshop/botkube-docs#199]
## Description

Helm chart version is not updated on final release cut. For all our releases, we had outdated Helm version badge and image tag, see:

https://github.com/kubeshop/botkube-docs/pull/198/commits/f9ed8a1fffccf20f50091927cc29ee5b671849c3

## Expected behavior

Released documentation has a valid version

Update [**Update versions in installation docs**](https://github.com/kubeshop/botkube-docs/blob/ba0bbc63a48bcade78a5cba4017690ed8ee89ba1/.github/workflows/release.yml#L47-L52
) step:
https://github.com/kubeshop/botkube-docs/blob/ba0bbc63a48bcade78a5cba4017690ed8ee89ba1/.github/workflows/release.yml#L47-L52

**Comment by huseyinbabal** [comment]
The root cause of this issue is not correctly updating versions, it is all about creating docs release before finalizing Botkube core stable release. So, we concluded with adding a validation to docs release before creating actual version.
