### ISSUE TITLE
Notification bar on botkube.io homepage

### ISSUE THREAD

**Issue by sanketsudake** [kubeshop/botkube-docs#48]
We should have a notification bar on the BotKube website, which highlights latest news from BotKube.

The news could be:
1. Latest release out from BotKube
2. Hacktoberfest participation announcment

Eg. https://css-tricks.com/wp-content/uploads/2011/08/notificationbar.png

**Comment by codenio** [comment]
a customizable permanent notification bar (without a close button), that can be enabled or disabled based on requirement..?

**Comment by sanketsudake** [comment]
1. It can be enabled or disabled.
2. This can be closed by the user.
3. Content of it can be customized as per the latest news from BotKube. This would require a merge in the repository every time an update is required.

**Comment by pkosiec** [comment]
Thank you - closing in favor of #80, as Docusaurus has it out of the box. Cheers!
