### ISSUE TITLE
Add spellcheck github action

### ISSUE THREAD

**Issue by PrasadG193** [kubeshop/botkube-docs#59]

**Comment by iamrajiv** [comment]
Hi @PrasadG193 can we consider this https://github.com/errata-ai/vale?

**Comment by pkosiec** [comment]
## Acceptance Criteria

- Integrate LanguageTool
- Integrate misspell check

- Run this on PR build
- Make it concurrent with current checks

Base on https://github.com/capactio/website/blob/main/.github/workflows/pr-build.yaml#L39-L63
