### ISSUE TITLE
Use Docusaurus for documentation website

### ISSUE THREAD

**Issue by pkosiec** [kubeshop/botkube-docs#80]
## Overview

Use Docusaurus as static docs site generator. 

## AC

- Start from a scratch on a separate branch
    - Split it to few PRs
- Use the latest version of Docusaurus (v2)
- Configure it according to the docs website https://docusaurus.io/docs
    - Use TypeScript, Sass/SCSS (or CSS in JS if supported already)
    - Disable blog
    - Use and configure `ideal-image` plugin to have responsive images
    - SEO (metadata, [meta image](https://docusaurus.io/docs/api/themes/configuration#meta-image))
    - Update basic branding (logo, colors, fonts)
    - Use Google Analytics site
    - Add cookie banner (e.g. https://github.com/buildo/react-cookie-banner)
    - Configure Algolia search
- Split documentation to:
    - Versioned docs for BotKube
    - Unversioned docs for Community (similarly as https://github.com/capactio/website) 
- Configure basic CI
- Configure eslint, Prettier

## Examples

- https://github.com/capactio/website - versioned docs, separate community docs, cookie banner, basic CI, eslint, prettier
- ⚠️ **Self-promotion alert** 😄  https://github.com/pkosiec/website - `ideal-image`, TypeScript, meta-image, Sass/SCSS , basic CI, eslint, prettier

## Reason

Currently, the botkube.io website has an outdated look and doesn't have support for documentation versioning.

**Comment by mszostok** [comment]
Here is already one change—removed `ingress.urlPath` :
- removed on develop: https://github.com/infracloudio/botkube/pull/532/files
- still mentioned in docs: https://github.com/infracloudio/botkube-docs/blame/master/content/installation/Teams/_index.md#L130

**Comment by pkosiec** [comment]
@madebyrogal This is already resolved, correct? If so, feel free to close it 🙂
