### ISSUE TITLE
Add release notes section

### ISSUE THREAD

**Issue by PrasadG193** [kubeshop/botkube-docs#83]
We should have a release notes sections to announce
- Announcements
- New features
- Breaking changes
- Upgrade notes
- etc
We already have automated CHANGELOG in place, we may need to refactor it or add separate sections for additional notes

**Comment by pkosiec** [comment]
Thanks Prasad - the release notes will be published as blog posts (e.g. https://kubeshop.io/blog/botkube-v013-release-notes) and we'll link to them on GitHub release (https://github.com/kubeshop/botkube/releases/tag/v0.13.0) and also a brand-new marketing site (coming soon). Closing it as resolved 👍
