### ISSUE TITLE
[Bug]: Image rendering issue on few screen sizes

### ISSUE THREAD

**Issue by PrasadG193** [kubeshop/botkube-docs#91]
### What happened?

BotKube arch image on the homepage is not getting rendered correctly on a few screen sizes/resolutions.
Above screenshot is on the following configuration:

1920 x 1080 16:9 - 14"

![image](https://user-images.githubusercontent.com/7098659/177830355-b947f5bd-7e45-44ba-acda-92efee2b7ff9.png)

### Version

1.0.0 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pkosiec** [comment]
Resolved as a part of #80
